#name: Deploy to GitHub Pages
#
#on:
#  push:
#    branches: ["main"]
#  workflow_dispatch:
#
#permissions:
#  contents: read
#  pages: write
#  id-token: write
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.14.1
#      - name: Install dependencies
#        run: |
#          npm install
#          npm ci
#      - name: List files before build
#        run: ls -la
#      - name: Build website
#        run: npm run build
#      - name: List files after build
#        run: |
#          ls -la
#          ls -la dist || echo "dist directory not found"
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1
#        with:
#          path: dist
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1


name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking dist directory..."
          ls -la dist || { echo "dist directory not found!"; exit 1; }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/
